/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/workflow` | `/workflow`; params?: Router.UnknownInputParams; } | { pathname: `/user/auth`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/language`; params?: Router.UnknownInputParams; } | { pathname: `/user/module`; params?: Router.UnknownInputParams; } | { pathname: `/user/personal`; params?: Router.UnknownInputParams; } | { pathname: `/user/theme`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/workflow` | `/workflow`; params?: Router.UnknownOutputParams; } | { pathname: `/user/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/user/language`; params?: Router.UnknownOutputParams; } | { pathname: `/user/module`; params?: Router.UnknownOutputParams; } | { pathname: `/user/personal`; params?: Router.UnknownOutputParams; } | { pathname: `/user/theme`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/workflow${`?${string}` | `#${string}` | ''}` | `/workflow${`?${string}` | `#${string}` | ''}` | `/user/auth${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/user/language${`?${string}` | `#${string}` | ''}` | `/user/module${`?${string}` | `#${string}` | ''}` | `/user/personal${`?${string}` | `#${string}` | ''}` | `/user/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/workflow` | `/workflow`; params?: Router.UnknownInputParams; } | { pathname: `/user/auth`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/language`; params?: Router.UnknownInputParams; } | { pathname: `/user/module`; params?: Router.UnknownInputParams; } | { pathname: `/user/personal`; params?: Router.UnknownInputParams; } | { pathname: `/user/theme`; params?: Router.UnknownInputParams; };
    }
  }
}
